"""empty message

Revision ID: 4e414d738594
Revises: e21eb9c59fe8
Create Date: 2021-02-08 12:13:17.310516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e414d738594'
down_revision = 'e21eb9c59fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'userPhotos', 'users', ['userAccountId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userPhotos', type_='foreignkey')
    # ### end Alembic commands ###
